<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-11T11:00:27 IST" name="Default suite" finished-at="2023-05-11T11:00:52 IST" duration-ms="24859">
    <groups>
    </groups>
    <test started-at="2023-05-11T11:00:27 IST" name="Default test" finished-at="2023-05-11T11:00:52 IST" duration-ms="24859">
      <class name="test.classes.ACCPLoginTest">
        <test-method is-config="true" signature="openBrowser()[pri:0, instance:test.classes.ACCPLoginTest@43f02ef2]" started-at="2023-05-11T11:00:27 IST" name="openBrowser" finished-at="2023-05-11T11:00:35 IST" duration-ms="8538" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openBrowser -->
        <test-method is-config="true" signature="loginToApp()[pri:0, instance:test.classes.ACCPLoginTest@43f02ef2]" started-at="2023-05-11T11:00:35 IST" name="loginToApp" finished-at="2023-05-11T11:00:49 IST" duration-ms="13150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginToApp -->
        <test-method signature="verifyPolicyNumber()[pri:0, instance:test.classes.ACCPLoginTest@43f02ef2]" started-at="2023-05-11T11:00:49 IST" name="verifyPolicyNumber" finished-at="2023-05-11T11:00:51 IST" duration-ms="1939" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failed : both results are different expected [AAP 0104677] but found [AAP 0104676]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failed : both results are different expected [AAP 0104677] but found [AAP 0104676]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at test.classes.ACCPLoginTest.verifyPolicyNumber(ACCPLoginTest.java:90)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyPolicyNumber -->
        <test-method is-config="true" signature="logoutFromApp(org.testng.ITestResult)[pri:0, instance:test.classes.ACCPLoginTest@43f02ef2]" started-at="2023-05-11T11:00:51 IST" name="logoutFromApp" finished-at="2023-05-11T11:00:52 IST" duration-ms="950" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyPolicyNumber status=FAILURE method=ACCPLoginTest.verifyPolicyNumber()[pri:0, instance:test.classes.ACCPLoginTest@43f02ef2] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApp -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:test.classes.ACCPLoginTest@43f02ef2]" started-at="2023-05-11T11:00:52 IST" name="closeBrowser" finished-at="2023-05-11T11:00:52 IST" duration-ms="117" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- test.classes.ACCPLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
